export const WORKSPACE_SUCCESS = "WORKSPACE_SUCCESS";
export const WORKSPACE_FAIL = "WORKSPACE_FAIL";

export const CREATE_WORKSPACE = "CREATE_WORKSPACE";
export const DELETE_WORKSPACE = "DELETE_WORKSPACE";
export const UPDATE_WORKSPACE = "UPDATE_WORKSPACE";
export const GET_WORKSPACE = "GET_WORKSPACE";
export const GET_WORKSPACES = "GET_WORKSPACES";